package com.tokoelektronik.dashboard;

import com.tokoelektronik.functions.DataBarang;
import com.tokoelektronik.functions.DataPelanggan;
import com.tokoelektronik.login.TokoElektronikLogin;
import java.awt.Color;
import java.awt.Component;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Time;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;

public class TokoElektronikDashboard extends javax.swing.JFrame {
    
    DefaultTableModel modelPelanggan = new DefaultTableModel();
    DefaultTableModel modelBarang = new DefaultTableModel();
    DataPelanggan dataPelanggan;
    Timer timer;

    /**
     * Creates new form TokoElektronikDashboard
     */
    public TokoElektronikDashboard() {
        
        initComponents();
        setColoumTable();
        setCannotBeChanged();
        setTabelBarang();
        setTabelPelanggan();
        setIdPelanggan();
        setIdBarang();
        setZero();
        setDashboard();
        setDateAndTime();
    }
    
    void setDateAndTime(){   
        ActionListener actionListener = new ActionListener(){
            @Override
            public void actionPerformed(ActionEvent e) {
                Date date = new Date();
                SimpleDateFormat format = new SimpleDateFormat("dd/MM/yyyy HH:mm:ss");
                txtTime.setText(format.format(date));
            }  
        };
        
        timer = new Timer(1000, actionListener);
        timer.setInitialDelay(0);
        timer.start();
    }
    
    void setColoumTable(){
        
        modelPelanggan.addColumn("ID Pelanggan");
        modelPelanggan.addColumn("Nama Pelanggan");
        modelPelanggan.addColumn("Umur");
        modelPelanggan.addColumn("No Telepon");
        tbPelanggan.setModel(modelPelanggan);
        
        modelBarang.addColumn("ID Barang");
        modelBarang.addColumn("Nama Barang");
        modelBarang.addColumn("Harga Barang");
        modelBarang.addColumn("Jumlah Barang");
        tbBarang.setModel(modelBarang);
     
    }
    
    void setDashboard(){
        txtDataBarang.setText(String.valueOf(tbBarang.getRowCount()) + " Barang");
        txtDataPelanggan.setText(String.valueOf(tbPelanggan.getRowCount()) + " Pelanggan");
    }
    
    void setZero(){
        
        fdHargaBarang.setText("0");
        fdJumlahBarang.setText("0");
        fdUmur.setText("0");
    }
    
    void setCannotBeChanged(){
        
        fdIdBarang.setEditable(false);
        fdIdPelanggan.setEditable(false);
    }
    
    void changePanel(Component a){
        
        pnBody.removeAll();
        pnBody.repaint();
        pnBody.revalidate();
        pnBody.add(a);
        pnBody.repaint();
        pnBody.revalidate();  
    }
    
    void emptyFieldsBarang(){
        
        fdIdBarang.setText("");
        fdNamaBarang.setText("");
        fdHargaBarang.setText("");
        fdJumlahBarang.setText("");  
    }
    
    void emptyFieldsPelanggan(){
        
        fdIdPelanggan.setText("");
        fdNamaPelanggan.setText("");
        fdUmur.setText("");
        fdNoTelepon.setText("");
    }
    
    void setTabelPelanggan(){
        
        modelPelanggan.addRow(new Object[]{
           "P0001",
            "Riswan",
            "19",
            "083190123213"
        });
        
        modelPelanggan.addRow(new Object[]{
           "P0002",
            "Wanto",
            "40",
            "083190123266"
        });
        
        modelPelanggan.addRow(new Object[]{
           "P0003",
            "Anjani",
            "24",
            "083122123266"
        });
        
    }
    
    void setTabelBarang(){
        
        modelBarang.addRow(new Object[]{
            "B0001",
            "Mouse",
            "20000",
            "20"
        });
        
        modelBarang.addRow(new Object[]{
            "B0002",
            "Keyboard",
            "15000",
            "10"
        });
        
        
    }
    
    void setIdBarang(){
        
        int i = 1;
        
        if(tbBarang.getRowCount() == 0){
            
            fdIdBarang.setText("B000"+i);
   
        }else{
            
            i = tbBarang.getRowCount() + 1;
            
            fdIdBarang.setText("B000"+i);
            
        }
  
    }
    
    void setIdPelanggan(){
        
        int i = 1;
        
        if(tbPelanggan.getRowCount() == 0){
            
            fdIdPelanggan.setText("P000"+i);
        }else{
            i = tbPelanggan.getRowCount() + 1;
            fdIdPelanggan.setText("P000"+i);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnHead = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnDashboard = new javax.swing.JButton();
        btnBarang = new javax.swing.JButton();
        btnPelanggan = new javax.swing.JButton();
        txtBar1 = new javax.swing.JLabel();
        txtBar2 = new javax.swing.JLabel();
        txtBar3 = new javax.swing.JLabel();
        txtTime = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        pnBody = new javax.swing.JPanel();
        spDashboard = new javax.swing.JScrollPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txtDataBarang = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        txtDataPelanggan = new javax.swing.JLabel();
        pnBarang = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbBarang = new javax.swing.JTable();
        btnHapusBarang = new javax.swing.JButton();
        btnUbahBarang = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        fdIdBarang = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        fdNamaBarang = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        fdHargaBarang = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        fdJumlahBarang = new javax.swing.JTextField();
        btnTambahBarang = new javax.swing.JButton();
        pnPelanggan = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbPelanggan = new javax.swing.JTable();
        btnHapusPelanggan = new javax.swing.JButton();
        btnUbahPelanggan = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        fdIdPelanggan = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        fdNamaPelanggan = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        fdUmur = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        fdNoTelepon = new javax.swing.JTextField();
        btnTambahPelanggan = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnHead.setBackground(new java.awt.Color(51, 153, 255));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/tokoelektronik/icons/userdashboard.png"))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Admin Toko Komputer");

        btnDashboard.setBackground(new java.awt.Color(255, 255, 255));
        btnDashboard.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnDashboard.setForeground(new java.awt.Color(255, 255, 255));
        btnDashboard.setText("DASHBOARD");
        btnDashboard.setBorder(null);
        btnDashboard.setContentAreaFilled(false);
        btnDashboard.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDashboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDashboardActionPerformed(evt);
            }
        });

        btnBarang.setBackground(new java.awt.Color(255, 255, 255));
        btnBarang.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnBarang.setForeground(new java.awt.Color(255, 255, 255));
        btnBarang.setText("DATA BARANG");
        btnBarang.setBorder(null);
        btnBarang.setContentAreaFilled(false);
        btnBarang.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBarangActionPerformed(evt);
            }
        });

        btnPelanggan.setBackground(new java.awt.Color(255, 255, 255));
        btnPelanggan.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnPelanggan.setForeground(new java.awt.Color(255, 255, 255));
        btnPelanggan.setText("DATA PELANGGAN");
        btnPelanggan.setBorder(null);
        btnPelanggan.setContentAreaFilled(false);
        btnPelanggan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPelanggan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPelangganActionPerformed(evt);
            }
        });

        txtBar1.setBackground(new java.awt.Color(255, 255, 255));
        txtBar1.setOpaque(true);

        txtBar2.setBackground(new java.awt.Color(255, 255, 255));
        txtBar2.setOpaque(true);

        txtBar3.setBackground(new java.awt.Color(255, 255, 255));
        txtBar3.setOpaque(true);

        txtTime.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        txtTime.setForeground(new java.awt.Color(255, 255, 255));
        txtTime.setText("2021/11/24 15:25:30");

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Selamat Datang, Admin");

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/tokoelektronik/icons/logout.png"))); // NOI18N
        jLabel8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnHeadLayout = new javax.swing.GroupLayout(pnHead);
        pnHead.setLayout(pnHeadLayout);
        pnHeadLayout.setHorizontalGroup(
            pnHeadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnHeadLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnHeadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnHeadLayout.createSequentialGroup()
                        .addGroup(pnHeadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnDashboard, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                            .addComponent(txtBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnHeadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnHeadLayout.createSequentialGroup()
                                .addComponent(txtBar2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtBar3, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnHeadLayout.createSequentialGroup()
                                .addComponent(btnBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnPelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(pnHeadLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel8))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnHeadLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(pnHeadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtTime, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
        );
        pnHeadLayout.setVerticalGroup(
            pnHeadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnHeadLayout.createSequentialGroup()
                .addGroup(pnHeadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnHeadLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(pnHeadLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTime)
                        .addGroup(pnHeadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnHeadLayout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(jLabel1))
                            .addGroup(pnHeadLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel8)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(pnHeadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnHeadLayout.createSequentialGroup()
                        .addGroup(pnHeadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnDashboard)
                            .addComponent(btnBarang)
                            .addComponent(btnPelanggan))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtBar2, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtBar3, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pnBody.setBackground(new java.awt.Color(255, 255, 255));
        pnBody.setLayout(new java.awt.CardLayout());

        spDashboard.setBackground(new java.awt.Color(255, 255, 255));
        spDashboard.setBorder(null);
        spDashboard.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setBackground(new java.awt.Color(51, 153, 255));
        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("DATA BARANG");
        jLabel3.setOpaque(true);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/tokoelektronik/icons/box.png"))); // NOI18N

        txtDataBarang.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        txtDataBarang.setText("100 Barang");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(txtDataBarang)))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtDataBarang)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel6.setBackground(new java.awt.Color(51, 153, 255));
        jLabel6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("DATA PELANGGAN");
        jLabel6.setOpaque(true);

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/tokoelektronik/icons/customer.png"))); // NOI18N

        txtDataPelanggan.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        txtDataPelanggan.setText("20 Pelanggan");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(48, Short.MAX_VALUE)
                .addComponent(txtDataPelanggan)
                .addGap(46, 46, 46))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtDataPelanggan)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(538, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(507, Short.MAX_VALUE))
        );

        spDashboard.setViewportView(jPanel3);

        pnBody.add(spDashboard, "card2");

        pnBarang.setBackground(new java.awt.Color(255, 255, 255));

        jLabel9.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel9.setText("Data Barang");

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));

        tbBarang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Barang", "Nama Barang", "Harga Barang", "Jumlah Barang"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tbBarang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbBarangMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbBarang);

        btnHapusBarang.setBackground(new java.awt.Color(51, 153, 255));
        btnHapusBarang.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnHapusBarang.setForeground(new java.awt.Color(255, 255, 255));
        btnHapusBarang.setText("Hapus");
        btnHapusBarang.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnHapusBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusBarangActionPerformed(evt);
            }
        });

        btnUbahBarang.setBackground(new java.awt.Color(51, 153, 255));
        btnUbahBarang.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnUbahBarang.setForeground(new java.awt.Color(255, 255, 255));
        btnUbahBarang.setText("Ubah");
        btnUbahBarang.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnUbahBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUbahBarangActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel11.setText("ID Barang");

        jLabel12.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel12.setText("Nama Barang");

        jLabel13.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel13.setText("Harga Barang");

        jLabel14.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel14.setText("Jumlah Barang");

        btnTambahBarang.setBackground(new java.awt.Color(51, 153, 255));
        btnTambahBarang.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnTambahBarang.setForeground(new java.awt.Color(255, 255, 255));
        btnTambahBarang.setText("Tambah");
        btnTambahBarang.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnTambahBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahBarangActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnBarangLayout = new javax.swing.GroupLayout(pnBarang);
        pnBarang.setLayout(pnBarangLayout);
        pnBarangLayout.setHorizontalGroup(
            pnBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnBarangLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnBarangLayout.createSequentialGroup()
                        .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 855, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(pnBarangLayout.createSequentialGroup()
                        .addGroup(pnBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addGroup(pnBarangLayout.createSequentialGroup()
                                .addGroup(pnBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnHapusBarang))
                                .addGap(57, 57, 57)
                                .addGroup(pnBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnBarangLayout.createSequentialGroup()
                                        .addComponent(btnTambahBarang)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnUbahBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(pnBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel14)
                                        .addComponent(fdHargaBarang, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)
                                        .addComponent(jLabel11)
                                        .addComponent(jLabel12)
                                        .addComponent(fdNamaBarang)
                                        .addComponent(jLabel13)
                                        .addComponent(fdJumlahBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(fdIdBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        pnBarangLayout.setVerticalGroup(
            pnBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnBarangLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnBarangLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnHapusBarang))
                    .addGroup(pnBarangLayout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(fdIdBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(fdNamaBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel13)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fdHargaBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fdJumlahBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pnBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTambahBarang)
                    .addComponent(btnUbahBarang))
                .addContainerGap(93, Short.MAX_VALUE))
        );

        pnBody.add(pnBarang, "card3");

        pnPelanggan.setBackground(new java.awt.Color(255, 255, 255));

        jLabel10.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel10.setText("Data Pelanggan");

        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));

        tbPelanggan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Pelanggan", "Nama Pelanggan", "Umur", "No Telepon"
            }
        ));
        tbPelanggan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbPelangganMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbPelanggan);

        btnHapusPelanggan.setBackground(new java.awt.Color(51, 153, 255));
        btnHapusPelanggan.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnHapusPelanggan.setForeground(new java.awt.Color(255, 255, 255));
        btnHapusPelanggan.setText("Hapus");
        btnHapusPelanggan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnHapusPelanggan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusPelangganActionPerformed(evt);
            }
        });

        btnUbahPelanggan.setBackground(new java.awt.Color(51, 153, 255));
        btnUbahPelanggan.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnUbahPelanggan.setForeground(new java.awt.Color(255, 255, 255));
        btnUbahPelanggan.setText("Ubah");
        btnUbahPelanggan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnUbahPelanggan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUbahPelangganActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel15.setText("ID Pelanggan");

        jLabel16.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel16.setText("Nama Pelanggan");

        jLabel17.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel17.setText("Umur");

        jLabel18.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel18.setText("No Telepon");

        btnTambahPelanggan.setBackground(new java.awt.Color(51, 153, 255));
        btnTambahPelanggan.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnTambahPelanggan.setForeground(new java.awt.Color(255, 255, 255));
        btnTambahPelanggan.setText("Tambah");
        btnTambahPelanggan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnTambahPelanggan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahPelangganActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnPelangganLayout = new javax.swing.GroupLayout(pnPelanggan);
        pnPelanggan.setLayout(pnPelangganLayout);
        pnPelangganLayout.setHorizontalGroup(
            pnPelangganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnPelangganLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnPelangganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator2)
                    .addGroup(pnPelangganLayout.createSequentialGroup()
                        .addGroup(pnPelangganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addGroup(pnPelangganLayout.createSequentialGroup()
                                .addGroup(pnPelangganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnHapusPelanggan))
                                .addGap(53, 53, 53)
                                .addGroup(pnPelangganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnPelangganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(pnPelangganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel16))
                                        .addComponent(fdNamaPelanggan, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                                        .addComponent(jLabel17)
                                        .addGroup(pnPelangganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(fdUmur, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addComponent(fdNoTelepon))
                                    .addComponent(fdIdPelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(pnPelangganLayout.createSequentialGroup()
                                        .addComponent(btnTambahPelanggan)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnUbahPelanggan)))))
                        .addGap(0, 203, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnPelangganLayout.setVerticalGroup(
            pnPelangganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnPelangganLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnPelangganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnPelangganLayout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnHapusPelanggan))
                    .addGroup(pnPelangganLayout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(fdIdPelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(fdNamaPelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel17)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fdUmur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fdNoTelepon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pnPelangganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTambahPelanggan)
                    .addComponent(btnUbahPelanggan))
                .addContainerGap(93, Short.MAX_VALUE))
        );

        pnBody.add(pnPelanggan, "card4");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnHead, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnBody, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnHead, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pnBody, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBarangActionPerformed
        // TODO add your handling code here:
        txtBar1.setBackground(new Color(255,255,255));
        txtBar2.setBackground(new Color(0,0,0));
        txtBar3.setBackground(new Color(255,255,255));
        changePanel(pnBarang);
        
    }//GEN-LAST:event_btnBarangActionPerformed

    private void btnDashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDashboardActionPerformed
        // TODO add your handling code here:
        txtBar1.setBackground(new Color(0,0,0));
        txtBar2.setBackground(new Color(255,255,255));
        txtBar3.setBackground(new Color(255,255,255));
        changePanel(spDashboard);
             
        
    }//GEN-LAST:event_btnDashboardActionPerformed

    private void btnPelangganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPelangganActionPerformed
        // TODO add your handling code here:
        txtBar1.setBackground(new Color(255,255,255));
        txtBar2.setBackground(new Color(255,255,255));
        txtBar3.setBackground(new Color(0,0,0));
        changePanel(pnPelanggan);
        
    }//GEN-LAST:event_btnPelangganActionPerformed

    private void btnHapusBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusBarangActionPerformed
        // TODO add your handling code here:
        
        if(tbBarang.getSelectedRow() == -1){
            
            if(tbBarang.getRowCount() == 0){
                
                JOptionPane.showMessageDialog(this, "Tidak ada data dalam tabel!!!");
 
            }else{
                
                JOptionPane.showMessageDialog(this, "Pilih data yang ingin dihapus!!!");
            }
            
        }else{
            
            
            
            int konfirmasi = JOptionPane.showConfirmDialog(this, "Apakah anda ingin menghapus data ini ?", "Delete", JOptionPane.YES_OPTION);
            
            if(konfirmasi == JOptionPane.YES_OPTION){
                
                modelBarang.removeRow(tbBarang.getSelectedRow());
                
                JOptionPane.showMessageDialog(this, "Data berhasil dihapus");
                
                setIdBarang();
                
                setDashboard();
                
            }
            
        }
    }//GEN-LAST:event_btnHapusBarangActionPerformed

    private void btnTambahBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahBarangActionPerformed
        // TODO add your handling code here:
        
        String idBarang = fdIdBarang.getText();
        String namaBarang = fdNamaBarang.getText();
        int hargaBarang = Integer.valueOf(fdHargaBarang.getText());
        int jumlahBarang = Integer.valueOf(fdJumlahBarang.getText());
        
        DataBarang barang = new DataBarang(idBarang, namaBarang, hargaBarang, jumlahBarang);
        
        if(barang.getIdBarang().equalsIgnoreCase("") || barang.getNamaBarang().equalsIgnoreCase("") || barang.getHargaBarang() == 0 || barang.getJumlahBarang() == 0){
            
            JOptionPane.showMessageDialog(this, "Ada field yang belum diisi!!!");
            
        }else{
            
            modelBarang.addRow(new Object[]{
                barang.getIdBarang(),
                barang.getNamaBarang(),
                barang.getHargaBarang(),
                barang.getJumlahBarang()
            });
            
            JOptionPane.showMessageDialog(this, "Data barang berhasil ditambahkan");
            emptyFieldsBarang();
            setIdBarang();
            setZero();
            setDashboard();
            
        }
        
        
    }//GEN-LAST:event_btnTambahBarangActionPerformed

    private void btnTambahPelangganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahPelangganActionPerformed
        // TODO add your handling code here:
        
        String idPelanggan = fdIdPelanggan.getText();
        String namaPelanggan = fdNamaPelanggan.getText();
        int umur = Integer.valueOf(fdUmur.getText());
        String noTelepon = fdNoTelepon.getText();
        
        DataPelanggan pelanggan = new DataPelanggan(idPelanggan, namaPelanggan, umur, noTelepon);
        
        if(pelanggan.getIdPelanggan().equals("") || pelanggan.getNamaPelanggan().equals("") || pelanggan.getUmur() == 0 || pelanggan.getNoTelepon().equals("")){
            JOptionPane.showMessageDialog(this, "Ada field yang belum diisi!!!");
            
            
        }else{
            modelPelanggan.addRow(new Object[]{
               pelanggan.getIdPelanggan(),
               pelanggan.getNamaPelanggan(),
               pelanggan.getUmur(),
               pelanggan.getNoTelepon()
                  
            });
            
            JOptionPane.showMessageDialog(this, "Data barang berhasil ditambahkan");
            emptyFieldsPelanggan();
            setIdPelanggan();
            setZero();
            setDashboard();
            
        }
    }//GEN-LAST:event_btnTambahPelangganActionPerformed

    private void btnHapusPelangganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusPelangganActionPerformed
        // TODO add your handling code here:
        
        if(tbPelanggan.getSelectedRow() == -1){
            
            if(tbPelanggan.getRowCount() == 0){
                
                JOptionPane.showMessageDialog(this, "Tidak ada data dalam tabel!!!");
                
            }else{
                
                JOptionPane.showMessageDialog(this, "Pilih data yang ingin dihapus!!!");
            }
            
        }else{
            
            int konfirmasi = JOptionPane.showConfirmDialog(this, "Apakah anda ingin menghapus data ini ?", "Delete", JOptionPane.YES_OPTION);
            
            if(konfirmasi == JOptionPane.YES_OPTION){
                
                modelPelanggan.removeRow(tbPelanggan.getSelectedRow());
                
                JOptionPane.showMessageDialog(this, "Data berhasil dihapus!!!");
                
                setIdPelanggan();
                
                setDashboard();
            }
            
        }
    }//GEN-LAST:event_btnHapusPelangganActionPerformed

    private void tbPelangganMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbPelangganMouseClicked
        // TODO add your handling code here:
        
        int row = tbPelanggan.getSelectedRow();
        
        if(tbPelanggan.getSelectedRow() == -1){
            
            if(tbPelanggan.getRowCount() == 0){
                
                JOptionPane.showMessageDialog(this, "Tidak ada data dalam tabel!!!");
            }
            
        }else{
            
            String idPelanggan = (String) modelPelanggan.getValueAt(row, 0);
            String namaPelanggan = (String) modelPelanggan.getValueAt(row, 1);
            int umur = Integer.parseInt(String.valueOf(modelPelanggan.getValueAt(row, 2)));
            String noTelepon = (String) modelPelanggan.getValueAt(row, 3);
            
            dataPelanggan = new DataPelanggan(idPelanggan, namaPelanggan, umur, noTelepon);
            
            fdIdPelanggan.setText(dataPelanggan.getIdPelanggan());
            fdNamaPelanggan.setText(dataPelanggan.getNamaPelanggan());
            fdUmur.setText(String.valueOf(dataPelanggan.getUmur()));
            fdNoTelepon.setText(dataPelanggan.getNoTelepon());
            
        }
    }//GEN-LAST:event_tbPelangganMouseClicked

    private void tbBarangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbBarangMouseClicked
        // TODO add your handling code here:
        
        if(tbBarang.getSelectedRow() == -1){
            
            if(tbBarang.getRowCount() == 0){
                
                JOptionPane.showMessageDialog(this, "Tidak ada data dalam tabel!!!");
                
            }
            
        }else{
            
            String idBarang = (String) modelBarang.getValueAt(tbBarang.getSelectedRow(), 0);
            String namaBarang = (String) modelBarang.getValueAt(tbBarang.getSelectedRow(), 1);
            int hargaBarang =  Integer.parseInt(String.valueOf(modelBarang.getValueAt(tbBarang.getSelectedRow(), 2)));
            int jumlahBarang = Integer.parseInt(String.valueOf(modelBarang.getValueAt(tbBarang.getSelectedRow(), 3)));
            
            DataBarang barang = new DataBarang(idBarang, namaBarang, hargaBarang, jumlahBarang);
            
            fdIdBarang.setText(barang.getIdBarang());
            fdNamaBarang.setText(barang.getNamaBarang());
            fdHargaBarang.setText(String.valueOf(barang.getHargaBarang()));
            fdJumlahBarang.setText(String.valueOf(barang.getJumlahBarang()));
            
        }
    }//GEN-LAST:event_tbBarangMouseClicked

    private void btnUbahPelangganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbahPelangganActionPerformed
        // TODO add your handling code here:
        
        int row = tbPelanggan.getSelectedRow();
      
        if(row == -1){
            
            if(tbPelanggan.getRowCount() == 0){
                
                JOptionPane.showMessageDialog(this, "Tidak ada data dalam tabel!!!");
                
            }else{
                
                JOptionPane.showMessageDialog(this, "Pilih data yang ingin diubah!!!");

            }
            
        }else{
            
            int konfirmasi = JOptionPane.showConfirmDialog(this, "Apakah anda ingin mengubah data ini ?", "Edit", JOptionPane.YES_OPTION);
            
            if(konfirmasi == JOptionPane.YES_OPTION){
                
                modelPelanggan.setValueAt(fdIdPelanggan.getText(), row, 0);
                modelPelanggan.setValueAt(fdNamaPelanggan.getText(), row, 1);
                modelPelanggan.setValueAt(fdUmur.getText(), row, 2);
                modelPelanggan.setValueAt(fdNoTelepon.getText(), row, 3); 
                
                JOptionPane.showMessageDialog(this, "Data berhasil diubah");
                
            }
            
            emptyFieldsPelanggan();
            setIdPelanggan();
            setZero();
   
        }
          
    }//GEN-LAST:event_btnUbahPelangganActionPerformed

    private void btnUbahBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbahBarangActionPerformed
        // TODO add your handling code here:
        
         int row = tbBarang.getSelectedRow();
      
        if(row == -1){
            
            if(tbBarang.getRowCount() == 0){
                
                JOptionPane.showMessageDialog(this, "Tidak ada data dalam tabel!!!");
                
            }else{
                
                JOptionPane.showMessageDialog(this, "Pilih data yang ingin diubah!!!");

            }
            
        }else{
            
            int konfirmasi = JOptionPane.showConfirmDialog(this, "Apakah anda ingin mengubah data ini ?", "Edit", JOptionPane.YES_OPTION);
            
            if(konfirmasi == JOptionPane.YES_OPTION){
                
                modelBarang.setValueAt(fdIdBarang.getText(), row, 0);
                modelBarang.setValueAt(fdNamaBarang.getText(), row, 1);
                modelBarang.setValueAt(fdHargaBarang.getText(), row, 2);
                modelBarang.setValueAt(fdJumlahBarang.getText(), row, 3); 
                
                JOptionPane.showMessageDialog(this, "Data berhasil diubah");
                
            }
            
            emptyFieldsBarang();
            setIdBarang();
            setZero();
   
        }
    }//GEN-LAST:event_btnUbahBarangActionPerformed

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        // TODO add your handling code here:
        TokoElektronikLogin tel = new TokoElektronikLogin();
        
        int konfirmasi = JOptionPane.showConfirmDialog(this, "Apakah anda ingin keluar?", "Logout", JOptionPane.YES_OPTION);
        
        if(konfirmasi == JOptionPane.YES_OPTION){
            
            JOptionPane.showMessageDialog(this, "Sampai jumpa, Admin");
            setVisible(false);
            tel.setLocationRelativeTo(null);
            tel.pack();
            tel.setVisible(true); 
        }
        
    }//GEN-LAST:event_jLabel8MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TokoElektronikDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TokoElektronikDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TokoElektronikDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TokoElektronikDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TokoElektronikDashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBarang;
    private javax.swing.JButton btnDashboard;
    private javax.swing.JButton btnHapusBarang;
    private javax.swing.JButton btnHapusPelanggan;
    private javax.swing.JButton btnPelanggan;
    private javax.swing.JButton btnTambahBarang;
    private javax.swing.JButton btnTambahPelanggan;
    private javax.swing.JButton btnUbahBarang;
    private javax.swing.JButton btnUbahPelanggan;
    private javax.swing.JTextField fdHargaBarang;
    private javax.swing.JTextField fdIdBarang;
    private javax.swing.JTextField fdIdPelanggan;
    private javax.swing.JTextField fdJumlahBarang;
    private javax.swing.JTextField fdNamaBarang;
    private javax.swing.JTextField fdNamaPelanggan;
    private javax.swing.JTextField fdNoTelepon;
    private javax.swing.JTextField fdUmur;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JPanel pnBarang;
    private javax.swing.JPanel pnBody;
    private javax.swing.JPanel pnHead;
    private javax.swing.JPanel pnPelanggan;
    private javax.swing.JScrollPane spDashboard;
    private javax.swing.JTable tbBarang;
    private javax.swing.JTable tbPelanggan;
    private javax.swing.JLabel txtBar1;
    private javax.swing.JLabel txtBar2;
    private javax.swing.JLabel txtBar3;
    private javax.swing.JLabel txtDataBarang;
    private javax.swing.JLabel txtDataPelanggan;
    private javax.swing.JLabel txtTime;
    // End of variables declaration//GEN-END:variables
}
